## Reading CSV file

In [59]:
import pandas as pd
df = pd.read_csv("superstore.csv")
df[df["Product Name"] == "Avery 508"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,US-2019-112326,2019/01/04,2019/01/08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2088,2089,US-2020-169677,2020/01/13,2020/01/15,Second Class,KS-16300,Karen Seio,Corporate,United States,Columbus,...,31907,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,9.820,2,0.0,4.8118
2793,2794,US-2020-158911,2020/07/05,2020/07/11,Standard Class,RS-19765,Roland Schwarz,Corporate,United States,Charlotte,...,28205,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
4292,4293,US-2021-100993,2021/02/05,2021/02/10,Standard Class,AZ-10750,Annie Zypern,Consumer,United States,San Diego,...,92037,West,OFF-LA-10003223,Office Supplies,Labels,Avery 508,14.730,3,0.0,7.2177
5974,5975,US-2021-124352,2021/10/15,2021/10/21,Standard Class,CD-12790,Cynthia Delaney,Home Office,United States,Oklahoma City,...,73120,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,29.460,6,0.0,14.4354
7944,7945,US-2022-101434,2022/06/20,2022/06/27,Standard Class,TR-21325,Toby Ritter,Consumer,United States,Belleville,...,07109,East,OFF-LA-10003223,Office Supplies,Labels,Avery 508,9.820,2,0.0,4.8118
10933,10934,CA-2014-112326,2014/01/04,2014/01/08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
11017,11018,CA-2017-101434,2017/06/20,2017/06/27,Standard Class,TR-21325,Toby Ritter,Consumer,United States,Belleville,...,7109,East,OFF-LA-10003223,Office Supplies,Labels,Avery 508,9.820,2,0.0,4.8118
12713,12714,CA-2016-124352,2016/10/15,2016/10/21,Standard Class,CD-12790,Cynthia Delaney,Home Office,United States,Oklahoma City,...,73120,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,29.460,6,0.0,14.4354
18335,18336,CA-2016-100993,2016/02/05,2016/02/10,Standard Class,AZ-10750,Annie Zypern,Consumer,United States,San Diego,...,92037,West,OFF-LA-10003223,Office Supplies,Labels,Avery 508,14.730,3,0.0,7.2177
18492,18493,US-2015-158911,2015/07/05,2015/07/11,Standard Class,RS-19765,Roland Schwarz,Corporate,United States,Charlotte,...,28205,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
18728,18729,CA-2015-169677,2015/01/13,2015/01/15,Second Class,KS-16300,Karen Seio,Corporate,United States,Columbus,...,31907,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,9.820,2,0.0,4.8118
20190,20191,US-2021-112326,2021/01/04,2021/01/08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
22276,22277,US-2022-169677,2022/01/13,2022/01/15,Second Class,KS-16300,Karen Seio,Corporate,United States,Columbus,...,31907,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,9.820,2,0.0,4.8118
22981,22982,US-2022-158911,2022/07/05,2022/07/11,Standard Class,RS-19765,Roland Schwarz,Corporate,United States,Charlotte,...,28205,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
24480,24481,US-2023-100993,2023/02/05,2023/02/10,Standard Class,AZ-10750,Annie Zypern,Consumer,United States,San Diego,...,92037,West,OFF-LA-10003223,Office Supplies,Labels,Avery 508,14.730,3,0.0,7.2177
26162,26163,US-2023-124352,2023/10/15,2023/10/21,Standard Class,CD-12790,Cynthia Delaney,Home Office,United States,Oklahoma City,...,73120,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,29.460,6,0.0,14.4354
28132,28133,US-2024-101434,2024/06/20,2024/06/27,Standard Class,TR-21325,Toby Ritter,Consumer,United States,Belleville,...,07109,East,OFF-LA-10003223,Office Supplies,Labels,Avery 508,9.820,2,0.0,4.8118
32141,32142,US-2018-158911,2018/07/05,2018/07/11,Standard Class,RS-19765,Roland Schwarz,Corporate,United States,Charlotte,...,28205,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
32180,32181,CA-2018-169677,2018/01/13,2018/01/15,Second Class,KS-16300,Karen Seio,Corporate,United States,Columbus,...,31907,South,OFF-LA-10003223,Office Supplies,Labels,Avery 508,9.820,2,0.0,4.8118

In [20]:
# Getting unique categoreis, sub categories and product names
product_names = df["Product Name"].unique()
categories = df["Category"].unique()
sub_cat = df["Sub-Category"].unique()

print(categories)

['Office Supplies' 'Furniture' 'Technology']

In [48]:
# Finding the cumliative sales and profit per category
cat_1 = df[df["Category"]==categories[0]]
cat_2 = df[df["Category"]==categories[1]]
cat_3 = df[df["Category"]==categories[2]]

all_cats = [cat_1,cat_2,cat_3] 
sales = []
profits = []

for x in all_cats:
    total_sales = x["Sales"].sum()
    sales.append(total_sales)
    
    total_profit = x["Profit"].sum()
    profits.append(total_profit)    

print(sales)

[2320067.1229999997, 2422013.5549, 2678721.4000000004]

In [46]:
# Creating a new table wth just categories
category_df = pd.DataFrame({
    "Category": categories,
    "Sales":sales,
    "Profit":profits
})

category_df

          Category         Sales       Profit
0  Office Supplies  2.320067e+06  399637.2214
1        Furniture  2.422014e+06   60926.4669
2       Technology  2.678721e+06  472045.5663

In [57]:
# For sub category of Technology
sub_cat_3 = cat_3["Sub-Category"].unique()
all_sub_cats = [] 
tech_sub_sales = []
tech_sub_profits = []

# Looping through sub cats of Technology
for i in sub_cat_3:
    temp = cat_3[cat_3["Sub-Category"] == i]
    total_sales = temp["Sales"].sum()
    tech_sub_sales.append(total_sales)
    
    total_profit = temp["Profit"].sum()
    tech_sub_profits.append(total_profit)

In [58]:
# Creating a new table wth just sub categories of technology
tech_df = pd.DataFrame({
    "Category": sub_cat_3,
    "Sales":tech_sub_sales,
    "Profit":tech_sub_profits
})

tech_df

      Category        Sales       Profit
0       Phones  1062006.036  145016.1910
1  Accessories   542664.914  136007.1823
2     Machines   596852.390   13286.1963
3      Copiers   477198.060  177735.9967

In [ ]:
# For sub category of Technology
sub_cat_3 = cat_3["Sub-Category"].unique()
all_sub_cats = [] 
tech_sub_sales = []
tech_sub_profits = []

# Looping through sub cats of Technology
for i in sub_cat_3:
    temp = cat_3[cat_3["Sub-Category"] == i]
    total_sales = temp["Sales"].sum()
    tech_sub_sales.append(total_sales)
    
    total_profit = temp["Profit"].sum()
    tech_sub_profits.append(total_profit)